const airportDictionary = {
    "Aarhus": "AAR",
    "Abadan": "ABD",
    "Abeche": "AEH",
    "Aberdeen": "ABZ",
    "Aberdeen (SD)": "ABR",
    "Abidjan": "ABJ",
    "Abilene (TX)": "ABI",
    "Abu Dhabi - Abu Dhabi International": "AUH",
    "Abuja - Nnamdi Azikiwe International Airport": "ABV",
    "Abu Rudeis": "AUE",
    "Abu Simbel": "ABS",
    "Acapulco": "ACA",
    "Accra - Kotoka International Airport": "ACC",
    "Adana": "ADA",
    "Addis Ababa - Bole International Airport": "ADD",
    "Adelaide": "ADL",
    "Aden - Aden International Airport": "ADE",
    "Adiyaman": "ADF",
    "Adler/Sochi": "AER",
    "Agades": "AJY",
    "Agadir": "AGA",
    "Agana (Hagåtña)": "SUM",
    "Aggeneys": "AGZ",
    "Aguadilla": "BQN",
    "Aguascaliente": "AGU",
    "Ahmedabad": "AMD",
    "Aiyura": "AYU",
    "Ajaccio": "AJA",
    "Akita": "AXT",
    "Akron (OH)": "CAK",
    "Akrotiri - RAF": "AKT",
    "Al Ain": "AAN",
    "Al Arish": "AAC",
    "Albany": "ALH",
    "Albany (GA)": "ABY",
    "Albany (NY) - Albany International Airport": "ALB",
    "Albi": "LBI",
    "Alborg": "AAL",
    "Albuquerque (NM)": "ABQ",
    "Albury": "ABX",
    "Alderney": "ACI",
    "Aleppo": "ALP",
    "Alesund": "AES",
    "Alexander Bay - Kortdoorn": "ALJ",
    "Alexandria - Borg el Arab Airport": "HBH",
    "Alexandria - El Nhouza Airport": "ALY",
    "Alexandria - Esler Field": "ESF",
    "Alfujairah (Fujairah)": "FJR",
    "Alghero Sassari": "AHO",
    "Algiers, Houari Boumediene Airport": "ALG",
    "Al Hoceima": "AHU",
    "Alicante": "ALC",
    "Alice Springs": "ASP",
    "Alldays": "ADY",
    "Allentown (PA)": "ABE",
    "Almaty (Alma Ata) - Almaty International Airport": "ALA",
    "Almeria": "LEI",
    "Alta": "ALF",
    "Altay": "AAT",
    "Altenrhein": "ACH",
    "Altoona (PA)": "AOO",
    "Altus": "AXS",
    "Amami": "ASJ",
    "Amarillo (TX)": "AMA",
    "Amazon Bay": "AZB",
    "Amman - Queen Alia International Airport": "AMM",
    "Amman - Amman-Marka International Airport": "ADJ",
    "Amritsar": "ATQ",
    "Amsterdam - Amsterdam Airport Schiphol": "AMS",
    "Anand": "QNB",
    "Anchorage (AK) - Ted Stevens Anchorage International": "ANC",
    "Ancona - Ancona Falconara Airport": "AOI",
    "Andorra La Vella - Heliport": "ALV",
    "Anguilla": "AXA",
    "Anjouan - Anjouan Airport": "AJN",
    "Ankara": "ANK",
    "Ankara - Esenboğa International Airport": "ESB",
    "Annaba": "AAE",
    "Ann Arbor (MI)": "ARB",
    "Annecy": "NCY",
    "Anniston (AL)": "ANB",
    "Antalya": "AYT",
    "Antananarivo (Tanannarive) - Ivato International Airport": "TNR",
    "Antigua, V.C. Bird International": "ANU",
    "Antwerp": "ANR",
    "Aomori": "AOJ",
    "Apia - Faleolo International Airport": "APW",
    "Appelton/Neenah/Menasha (WI)": "ATW",
    "Aqaba": "AQJ",
    "Aracaju": "AJU",
    "Arkhangelsk": "ARH",
    "Arusha": "ARK",
    "Araxos": "GPA",
    "Arlit": "RLT",
    "Arrecife/Lanzarote": "ACE",
    "Aruba - Reina Beatrix International, Oranjestad": "AUA",
    "Asheville (NC)": "AVL",
    "Ashgabat - Saparmurat Turkmenbashy Int. Airport": "ASB",
    "Asmara - Asmara International": "ASM",
    "Aspen, (CO) - Aspen-Pitkin County Airport": "ASE",
    "Assiut": "ATZ",
    "Astana - Astana International Airport": "TSE",
    "Asuncion - Asunción International Airport": "ASU",
    "Aswan - Daraw Airport": "ASW",
    "Athens - Elefthérios Venizélos International Airport": "ATH",
    "Athens, Hellinikon Airport": "HEW",
    "Athens (GA)": "AHN",
    "Athens (OH)": "ATO",
    "Atlanta (GA) - Hartsfield Atlanta International Airport": "ATL",
    "Atlantic City (NJ) - Atlantic City International": "ACY",
    "Attawapiskat, NT": "YAT",
    "Auckland - Auckland International Airport": "AKL",
    "Augsburg - Augsburg Airport": "AGB",
    "Augusta (GA)": "AGS",
    "Augusta (ME) - Augusta State Airport": "AUG",
    "Aurillac": "AUR",
    "Austin (TX) - Austin-Bergstrom Airport": "AUS",
    "Ayawasi": "AYW",
    "Ayers Rock - Connellan": "AYQ",
    "Ayr": "AYR",
    "Badajoz": "BJZ",
    "Bagdad - Baghdad International Airport": "BGW",
    "Bagdogra": "IXB",
    "Bahamas - Lynden Pindling International Airport": "NAS",
    "Bahawalpur": "BHV",
    "Bahrain - Bahrain International Airport": "BAH",
    "Bakersfield (CA)": "BFL",
    "Baku - Heydar Aliyev International Airport": "BAK",
    "Ballina": "BNK",
    "Baltimore (MD) - Washington International Airport": "BWI",
    "Bamaga": "ABM",
    "Bamako - Bamako-Sénou International Airport": "BKO",
    "Bambari": "BBY",
    "Bandar Seri Begawan - Brunei International Airport": "BWN",
    "Bandung - Husein Sastranegara International Airport": "BDO",
    "Bangalore": "BLR",
    "Bangassou": "BGU",
    "Bangkok, Don Muang": "DMK",
    "Bangkok, Suvarnabhumi International": "BKK",
    "Bangor (ME)": "BGR",
    "Bangui - M'Poko International Airport": "BGF",
    "Banjul - Banjul International Airport (Yundum International)": "BJL",
    "Bannu": "BNP",
    "Barcelona": "BCN",
    "Barcelona": "BLA",
    "Bardufoss": "BDU",
    "Bari": "BRI",
    "Barisal": "BZL",
    "Baroda": "BDQ",
    "Barra (the famous tidal beach landing)": "BRR",
    "Barranquilla": "BAQ",
    "Basel": "BSL",
    "Basel/Mulhouse": "EAP",
    "Basra, Basrah": "BSR",
    "Basse-Terre - Pointe-à-Pitre International Airport": "PTP",
    "Basseterre - Robert L. Bradshaw International Airport": "SKB",
    "Bastia": "BIA",
    "Baton Rouge (LA) - Baton Rouge Metropolitan Airport": "BTR",
    "Bayreuth - Bindlacher-Berg": "BYU",
    "Beaumont/Pt. Arthur (TX)": "BPT",
    "Beckley (WV)": "BKW",
    "Beef Island - Terrance B. Lettsome": "EIS",
    "Beijing": "PEK",
    "Beijing - Nanyuan Airport": "NAY",
    "Beira": "BEW",
    "Beirut - Beirut Rafic Hariri International Airport": "BEY",
    "Belem - Val de Cans International Airport": "BEL",
    "Belfast - George Best Belfast City Airport": "BHD",
    "Belfast - Belfast International Airport": "BFS",
    "Belgaum": "IXG",
    "Belgrad (Beograd) - Belgrade Nikola Tesla International": "BEG",
    "Belize City - Philip S.W.Goldson International": "BZE",
    "Bellingham (WA)": "BLI",
    "Belo Horizonte - Tancredo Neves International Airport": "CNF",
    "Bemidji (MN)": "BJI",
    "Benbecula": "BEB",
    "Benghazi (Bengasi)": "BEN",
    "Benguela": "BUG",
    "Benton Harbour (MI)": "BEH",
    "Berberati": "BBT",
    "Bergamo/Milan - Orio Al Serio": "BGY",
    "Bergen": "BGO",
    "Bergerac - Roumanieres": "EGC",
    "Berlin": "BER",
    "Berlin, Schoenefeld": "SXF",
    "Berlin, Tegel": "TXL",
    "Berlin, Tempelhof (ceased operating in 2008)": "THF",
    "Bermuda - L.F. Wade International Airport": "BDA",
    "Berne, Bern-Belp": "BRN",
    "Berne, Railway Service": "ZDJ",
    "Bethel (AK)": "BET",
    "Bhopal": "BHO",
    "Bhubaneswar": "BBI",
    "Biarritz": "BIQ",
    "Bilbao": "BIO",
    "Billings (MT)": "BIL",
    "Billund": "BLL",
    "Bintulu": "BTU",
    "Biraro": "IRO",
    "Birmingham - Birmingham International Airport": "BHX",
    "Birmingham (AL)": "BHM",
    "Bishkek - Manas International Airport": "FRU",
    "Bismarck (ND) - Bismarck Municipal Airport": "BIS",
    "Bissau - Osvaldo Vieiro International Airport": "BXO",
    "Blackpool": "BLK",
    "Blackwater": "BLT",
    "Blantyre (Mandala) - Chileka International Airport": "BLZ",
    "Blenheim": "BHE",
    "Bloemfontein - Bloemfontein Airport": "BFN",
    "Bloomington (IL)": "BMI",
    "Bloomington (IN)": "BMG",
    "Bluefield (WV)": "BLF",
    "Boa Vista": "BVB",
    "Bobo/Dioulasso": "BOY",
    "Bodo": "BOO",
    "Bodrum - Milas Airport": "BJV",
    "Bogota - El Nuevo Dorado International Airport": "BOG",
    "Boise (ID) - Boise Air Terminal": "BOI",
    "Bologna": "BLQ",
    "Bombay (Mumbai) - Chhatrapati Shivaji International": "BOM",
    "Bonaire": "BON",
    "Bonaventure, PQ": "YVB",
    "Bora Bora": "BOB",
    "Bordeaux - Bordeaux Airport": "BOD",
    "Borrego Springs (CA)": "BXS",
    "Boston (MA) - General Edward Lawrence Logan": "BOS",
    "Bouake": "BYK",
    "Bourgas/Burgas": "BOJ",
    "Bournemouth": "BOH",
    "Bowen": "ZBO",
    "Bozeman (MT)": "BZN",
    "Bradford/Warren (PA) /Olean (NY)": "BFD",
    "Brainerd (MN)": "BRD",
    "Brampton Island": "BMP",
    "Brasilia - President Juscelino Kubitschek International": "BSB",
    "Bratislava - M. R. Štefánik Airport": "BTS",
    "Brazzaville - Maya-Maya Airport": "BZV",
    "Bremen - Bremen Airport (Flughafen Bremen)": "BRE",
    "Brescia, Montichiari": "VBS",
    "Brest": "BES",
    "Bria": "BIV",
    "Bridgeport (CT)": "BDR",
    "Bridgetown - Grantley Adams International": "BGI",
    "Brindisi": "BDS",
    "Brisbane": "BNE",
    "Bristol": "BRS",
    "Broennoeysund": "BNN",
    "Broken Hill": "BHQ",
    "Brookings (SD)": "BKX",
    "Broome": "BME",
    "Brunswick (GA)": "BQK",
    "Brussels - Brussels Airport": "BRU",
    "Bucaramanga": "BGA",
    "Bucharest": "BUH",
    "Bucharest - Henri Coandă International Airport": "OTP",
    "Budapest - Budapest Ferihegy International Airport": "BUD",
    "Buenos Aires": "BUE",
    "Buenos Aires, Ezeiza International Airport": "EZE",
    "Buenos Aires, Jorge Newbery": "AEP",
    "Buffalo Range": "BFO",
    "Buffalo/Niagara Falls (NY)": "BUF",
    "Bujumbura - Bujumbura International Airport": "BJM",
    "Bulawayo": "BUQ",
    "Bullhead City (NV)": "BHC",
    "Bundaberg": "BDB",
    "Burbank (CA)": "BUR",
    "Burlington IA": "BRL",
    "Burlington (VT)": "BTV",
    "Burnie (Wynyard)": "BWT",
    "Butte (MT)": "BTM",
    "Cabinda": "CAB",
    "Cagliari": "CAG",
    "Cairns": "CNS",
    "Cairo - Cairo International Airport": "CAI",
    "Calama - El Loa": "CJC",
    "Calcutta (Kolkata) - Netaji Subhas Chandra": "CCU",
    "Calgary - Calgary International Airport": "YYC",
    "Cali": "CLO",
    "Calicut": "CCJ",
    "Calvi": "CLY",
    "Cambridge Bay": "YCB",
    "Cambrigde": "CRN",
    "Campbell River": "YBL",
    "Campo Grande": "CGR",
    "Canberra": "CBR",
    "Cancun": "CUN",
    "Canaan": "CYN",
    "Candiac": "YCD",
    "Cape Town - Cape Town International Airport": "CPT",
    "Capri": "CAP",
    "Caracas - Simón Bolívar International Airport": "CCS",
    "Cardiff": "CWL",
    "Carlsbad (CA)": "CLD",
    "Carthage": "TUN",
    "Cascavel": "CAC",
    "Casablanca - Mohammed V International Airport": "CMN",
    "Catania": "CTA",
    "Catumbela": "CTB",
    "Cayenne - Cayenne-Rochambeau Airport": "CAY",
    "Cedar City (UT)": "CDC",
    "Cedar Rapids (IA)": "CID",
    "Ceiba": "RVR",
    "Chachapoyas": "CHH",
    "Chadron (NE)": "CDR",
    "Chalon-sur-Saône": "XCD",
    "Chambery": "CMF",
    "Chania": "CHQ",
    "Chengdu - Chengdu Shuangliu International Airport": "CTU",
    "Chennai": "MAA",
    "Cherepovets": "CEE",
    "Chihuahua": "CUU",
    "Chimoio": "VBW",
    "Chisinau - Chișinău International Airport": "KIV",
    "Chongqing": "CKG",
    "Christchurch": "CHC",
    "Cincinnati (OH)": "CVG",
    "Clarksburg (WV)": "CKB",
    "Clermont-Ferrand": "CFE",
    "Cleveland (OH) - Cleveland Hopkins International": "CLE",
    "Cluj-Napoca": "CLJ",
    "Coimbra": "CBP",
    "Colima": "CLQ",
    "Colmar": "CMR",
    "Cologne/Bonn": "CGN",
    "Columbus (OH)": "CMH",
    "Conakry - Conakry International Airport": "CKY",
    "Concord (CA)": "CCR",
    "Concordia (ARG)": "COC",
    "Coonabarabran": "COB",
    "Copenhagen - Copenhagen Airport": "CPH",
    "Córdoba": "COR",
    "Corfu": "CFU",
    "Corsica": "BIA",
    "Costa Rica - San José Juan Santamaría International Airport": "SJO",
    "Cotonou": "COO",
    "Cozumel": "CZM",
    "Craig (AK)": "CGA",
    "Crescent City (CA)": "CEC",
    "Cuiabá": "CGB",
    "Curacao": "CUR",
    "Cuttack": "CTC",
    "Da Nang": "DAD",
    "Dakar - Léopold Sédar Senghor International Airport": "DKR",
    "Dalaman": "DLM",
    "Dallas (DFW)": "DFW",
    "Dallas (DAL)": "DAL",
    "Dalton (GA)": "DNN",
    "Damascus - Damascus International Airport": "DAM",
    "Danang": "DAD",
    "Dapto": "DPT",
    "Dar Es Salaam": "DAR",
    "Dawson Creek": "YDQ",
    "Dayton (OH)": "DAY",
    "Deauville": "DOL",
    "Debrecen": "DEB",
    "Delhi": "DEL",
    "Dells (WI)": "DLH",
    "Denpasar - Ngurah Rai International Airport": "DPS",
    "Denizli": "DNZ",
    "Denver (CO)": "DEN",
    "Des Moines (IA)": "DSM",
    "Detroit (MI)": "DTW",
    "Dijon": "DIJ",
    "Dillingham (AK)": "DLG",
    "Djerba": "DJE",
    "Djibouti - Djibouti-Ambouli International Airport": "JIB",
    "Dodo": "DDP",
    "Doha - Hamad International Airport": "DOH",
    "Dole": "DLE",
    "Dominica - Douglas-Charles Airport": "DOM",
    "Donetsk": "DOK",
    "Dortmund": "DTM",
    "Douala - Douala International Airport": "DLA",
    "Dresden": "DRS",
    "Dubai - Dubai International Airport": "DXB",
    "Dublin - Dublin Airport": "DUB",
    "Dubuque (IA)": "DBQ",
    "Dushanbe - Dushanbe International Airport": "DYU",
    "Durango": "DGO",
    "Durham (NC)": "DUR",
    "Dutch Harbor (AK)": "DUT",
    "Dzaoudzi - Dzaoudzi Pamandzi International Airport": "DZA",
    "Eau Claire (WI)": "EAU",
    "Edinburgh": "EDI",
    "Edmonton": "YEG",
    "Eilat": "ETH",
    "Eindhoven": "EIN",
    "El Dorado": "ELD",
    "El Paso (TX)": "ELP",
    "El Salvador - El Salvador International Airport": "SAL",
    "Eldoret": "EDL",
    "Eli": "EIL",
    "Elko (NV)": "EKO",
    "Eloy": "LOH",
    "Emanuel (Mexico)": "ZMT",
    "Entebbe - Entebbe International Airport": "EBB",
    "Epinal": "EPL",
    "Erechim": "ERJ",
    "Erfurt": "ERF",
    "Erzurum": "ERZ",
    "Esbjerg": "EBJ",
    "Essen": "ESS",
    "Estero": "ESR",
    "Ethiopia - Addis Ababa Bole International Airport": "ADD",
    "Eugene (OR)": "EUG",
    "Eumam": "EUM",
    "Eureka (CA)": "EKA",
    "Evansville (IN)": "EVV",
    "Fakarava": "FAV",
    "Fargo (ND)": "FAR",
    "Fasa": "FAS",
    "Fes - Fès–Saïs Airport": "FEZ",
    "Florence (SC)": "FLO",
    "Florence (IT)": "FLR",
    "Fochville": "FOC",
    "Fort Lauderdale (FL)": "FLL",
    "Fort Myers (FL)": "RSW",
    "Fort Smith (AR)": "FSM",
    "Fort St. John": "YXJ",
    "Fort Worth (TX)": "FTW",
    "Fresno (CA)": "FAT",
    "Fuerteventura": "FUE",
    "Fukuoka": "FUK",
    "Funchal - Madeira": "FNC",
    "Gaborone": "GBE",
    "Gainesville (FL)": "GNV",
    "Galapagos": "GPS",
    "Gambia - Banjul International Airport (Yundum International)": "BJL",
    "Gander (NF)": "YQX",
    "Gao": "GAO",
    "Garoua": "GOU",
    "Gatwick": "LGW",
    "Geneva - Genève Aéroport": "GVA",
    "Georgetown - Owen Roberts International Airport": "GCM",
    "Gerona": "GRO",
    "Ghana - Kotoka International Airport": "ACC",
    "Gibraltar - Gibraltar Airport": "GIB",
    "Gifu": "GIF",
    "Gilgit": "GIL",
    "Gimpo": "GMP",
    "Girona": "GRO",
    "Glasgow": "GLA",
    "Glasgow - Prestwick": "PIK",
    "Glendale": "GDL",
    "Goa - Dabolim Airport": "GOI",
    "Gold Coast": "OOL",
    "Gold Beach (OR)": "GLD",
    "Goma": "GOM",
    "Gonzales (TX)": "ZGZ",
    "Goodland (KS)": "GLD",
    "Gorakhpur": "GOP",
    "Gothenburg": "GOT",
    "Grand Canyon Village (AZ)": "GCN",
    "Grand Junction (CO)": "GJT",
    "Grand Rapids (MI)": "GRR",
    "Grangemouth": "GRM",
    "Grave": "GRV",
    "Greenville (SC)": "GVL",
    "Greensboro (NC)": "GBO",
    "Greensboro": "GBO",
    "Greenville (TX)": "GVX",
    "Gresham": "GSM",
    "Grimsby": "GMB",
    "Guadalajara - Don Miguel Hidalgo y Costilla International": "GDL",
    "Guadalajara": "GDL",
    "Guam - A.B. Won Pat International Airport": "GUM",
    "Guangzhou - Guangzhou Baiyun International Airport": "CAN",
    "Guarapuava": "GPB",
    "Guatemala City": "GUA",
    "Guayaquil": "GYE",
    "Guinea": "GUI",
    "Gurugram": "GUR",
    "Gyeongju": "GJJ",
    "Hachioji": "HAC",
    "Hainan": "HAK",
    "Haikou": "HAK",
    "Halle": "LEJ",
    "Hammond": "HMO",
    "Hamburg": "HAM",
    "Hamilton": "YHM",
    "Hancock (MI)": "CMX",
    "Hangzhou": "HGH",
    "Hannover": "HAJ",
    "Harare": "HRE",
    "Harrisburg (PA)": "MDT",
    "Hattiesburg (MS)": "HBG",
    "Haïti - Port-au-Prince Airport": "PAP",
    "Hobart": "HBA",
    "Hokkaido": "OKD",
    "Honaunau": "KAP",
    "Honolulu (HI)": "HNL",
    "Honiara": "HIR",
    "Houston (IAH)": "IAH",
    "Houston (HOU)": "HOU",
    "Hyderabad": "HYD",
    "Iquitos": "IQT",
    "Istanbul - Istanbul Airport": "IST",
    "Ithaca (NY)": "ITH",
    "Jackson (MI)": "JXN",
    "Jackson Hole (WY)": "JAC",
    "Jacksonville (FL)": "JAX",
    "Jakarta - Soekarno–Hatta International Airport": "CGK",
    "Jamaica - Norman Manley International Airport": "KIN",
    "Jamaica - Sangster International Airport": "MBJ",
    "Janssen": "JAN",
    "Jinan": "TNA",
    "Jodhpur": "JDH",
    "Johannesburg - OR Tambo International Airport": "JNB",
    "Juba": "JUB",
    "Jujuy": "JUJ",
    "Juliaca": "JUL",
    "Kahului (HI)": "OGG",
    "Kalgoorlie": "KGI",
    "Kampala - Entebbe International Airport": "EBB",
    "Kansas City (MO)": "MCI",
    "Kauai": "LIH",
    "Kavala": "KVA",
    "Kaysville": "KAY",
    "Kebili": "KEB",
    "Kerala": "TRV",
    "Kigali": "KGL",
    "Killeen (TX)": "GRK",
    "Kinshasa - N'Djili Airport": "FIH",
    "Kingston (Jamaica)": "KIN",
    "Kinshasa": "FIH",
    "Kitchener": "YKF",
    "Kobe": "UKB",
    "Koh Samui": "USM",
    "Kolkata": "CCU",
    "Komatsu": "KMQ",
    "Kona (HI)": "KOA",
    "Kota Kinabalu": "BKI",
    "Kraków": "KRK",
    "Kumasi": "KMS",
    "Kunming": "KMG",
    "Kuwait City": "KWI",
    "La Paz": "LPB",
    "Lagos": "LOS",
    "Lahore": "LHE",
    "Lake Charles (LA)": "LCH",
    "Lake Havasu City (AZ)": "HII",
    "Lamezia Terme": "SUF",
    "Lanzarote": "ACE",
    "Laredo (TX)": "LRD",
    "Las Vegas (NV)": "LAS",
    "Lima - Jorge Chávez International Airport": "LIM",
    "Lindau": "LDB",
    "Lisbon": "LIS",
    "Little Rock (AR)": "LIT",
    "Londrina": "LDB",
    "London - Heathrow": "LHR",
    "London - Gatwick": "LGW",
    "Longview (TX)": "GGG",
    "Lorca": "LOR",
    "Los Angeles (LAX)": "LAX",
    "Los Cabos": "SJD",
    "Luanda - Quatro de Fevereiro Airport": "LAD",
    "Lubumbashi": "FBM",
    "Lusaka": "LUN",
    "Luxor": "LXR",
    "Lyon": "LYS",
    "Madrid": "MAD",
    "Mahe": "SEZ",
    "Mahé Island": "SEZ",
    "Malaga": "AGP",
    "Málaga": "AGP",
    "Malawi - Lilongwe International Airport": "LLW",
    "Malta - Malta International Airport": "MLA",
    "Managua": "MGA",
    "Manado": "MDC",
    "Manchester": "MAN",
    "Manila": "MNL",
    "Mannheim": "MHG",
    "Marrakech - Menara Airport": "RAK",
    "Marseille": "MRS",
    "Martinique - Fort-de-France": "FDF",
    "Medan": "KNO",
    "Melbourne": "MEL",
    "Memphis (TN)": "MEM",
    "Mérida": "MID",
    "Moscow": "DME",
    "Mossoro": "MVF",
    "Munich": "MUC",
    "Muskegon (MI)": "MKG",
    "Myrtle Beach (SC)": "MYR",
    "Nairobi - Jomo Kenyatta International Airport": "NBO",
    "Nakhon Ratchasima": "NAK",
    "Nairobi": "NBO",
    "Nanaimo": "YCD",
    "Naples (FL)": "APF",
    "Nassau": "NAS",
    "Nîmes": "FNI",
    "Ningbo": "NGB",
    "Nizhny Novgorod": "GOJ",
    "Nouakchott": "NKC",
    "Nouméa - La Tontouta International Airport": "NOU",
    "Nova Iguaçu": "NIG",
    "Nuremberg": "NUE",
    "Oaxaca": "OAX",
    "Oberammergau": "OBM",
    "Odessa": "ODS",
    "Oklahoma City (OK)": "OKC",
    "Olongapo": "SFS",
    "Olsztyn": "SZY",
    "Oranjestad": "AUA",
    "Oran": "ORN",
    "Osaka - Kansai International Airport": "KIX",
    "Osaka - Itami": "ITM",
    "Oslo": "OSL",
    "Ostend": "OST",
    "Ouch": "OUC",
    "Oulu": "OUL",
    "Paderborn": "PAD",
    "Palanga": "PLQ",
    "Palermo": "PMO",
    "Palma": "PMI",
    "Panama City - Tocumen International Airport": "PTY",
    "Papeete - Fa'a'ā International Airport": "PPT",
    "Paris - Charles de Gaulle": "CDG",
    "Paris - Orly": "ORY",
    "Patna": "PAT",
    "Perpignan": "PGF",
    "Peshawar": "PEW",
    "Pointe-à-Pitre": "PTP",
    "Port Elizabeth": "PLZ",
    "Port Harcourt": "PHC",
    "Port Moresby": "POM",
    "Porto Alegre": "POA",
    "Porto": "OPO",
    "Prague": "PRG",
    "Pretoria": "PRY",
    "Puebla": "PBC",
    "Pucón": "ZPC",
    "Punta Arenas": "PUQ",
    "Puerto Plata": "POP",
    "Puerto Rico": "SJU",
    "Quito": "UIO",
    "Raleigh (NC)": "RAL",
    "Rangoon": "RGN",
    "Ras Al Khaimah": "RKT",
    "Rasht": "RAS",
    "Ravensburg": "RVS",
    "Reno (NV)": "RNO",
    "Reykjavik": "KEF",
    "Riga": "RIX",
    "Riyadh - King Khalid International Airport": "RUH",
    "Rome": "FCO",
    "Rostov-on-Don": "ROV",
    "Riyadh": "RUH",
    "Ruang": "RUQ",
    "Saint Barthélemy": "SBH",
    "Saint Denis": "RUN",
    "Saint Lucia - Hewanorra International Airport": "UVF",
    "Saint Pierre": "ZSE",
    "Saint-Tropez": "TLN",
    "Saint-Tropez": "TLN",
    "Sana'a": "SAH",
    "San Diego (CA)": "SAN",
    "San Francisco (CA)": "SFO",
    "San Jose (CA)": "SJC",
    "San Juan": "SJU",
    "San Salvador": "SAL",
    "San Sebastián": "EAS",
    "Santiago": "SCL",
    "Santo Domingo": "SDQ",
    "São Luís": "SLZ",
    "Sapporo": "CTS",
    "Sarajevo": "SJJ",
    "Sault Ste. Marie": "YAM",
    "Savannah (GA)": "SAV",
    "Sao Paulo": "GRU",
    "Seattle (WA)": "SEA",
    "Seoul - Incheon International Airport": "ICN",
    "Shanghai - Pudong International Airport": "PVG",
    "Sharjah": "SHJ",
    "Shenyang": "SHE",
    "Sialkot": "SKT",
    "Singapore - Singapore Changi Airport": "SIN",
    "Sion": "SIR",
    "Skopje": "SKP",
    "Sofia": "SOF",
    "Solomon Islands - Honiara International Airport": "HIR",
    "Somalia - Aden Adde International Airport": "MGQ",
    "South Bend (IN)": "SBN",
    "Southampton": "SOU",
    "Soviets": "SOV",
    "St. John's": "YYT",
    "Stavanger": "SVG",
    "Stockholm - Arlanda": "ARN",
    "Stockholm - Bromma": "BMA",
    "Stuttgart": "EDDS",
    "Sukhothai": "THS",
    "Sumba": "TMC",
    "Sumbawa": "SWJ",
    "Surabaya": "SUB",
    "Syracuse (NY)": "SYR",
    "Tainan": "TNN",
    "Taipei": "TPE",
    "Tbilisi": "TBS",
    "Tehran - Tehran Imam Khomeini International Airport": "IKA",
    "Tegucigalpa": "TGU",
    "Tel Aviv": "TLV",
    "Tenerife": "TFS",
    "Terre Haute (IN)": "HUF",
    "Thimphu": "PBH",
    "Tianjin": "TSN",
    "Toulouse": "TLS",
    "Tokyo - Narita": "NRT",
    "Tokyo - Haneda": "HND",
    "Toronto": "YYZ",
    "Toulouse": "TLS",
    "Trieste": "TRS",
    "Trujillo": "TRU",
    "Tucson (AZ)": "TUS",
    "Tunis": "TUN",
    "Ulaanbaatar": "ULN",
    "Ulaanbaatar - Buyant-Ukhaa International Airport": "ULN",
    "Ulan-Ude": "UUD",
    "Uluru": "AYQ",
    "Utrecht": "UTR",
    "Vadodara": "BDQ",
    "Vancouver": "YVR",
    "Varna": "VAR",
    "Vatican City": "VTC",
    "Victoria (BC)": "YVR",
    "Vila Real": "VRL",
    "Vilnius": "VNO",
    "Vinh": "VII",
    "Warsaw": "WAW",
    "Wellington": "WLG",
    "West Palm Beach (FL)": "PBI",
    "Wichita (KS)": "ICT",
    "Winnipeg": "YWG",
    "Wroclaw": "WRO",
    "Xiamen": "XMN",
    "Yamagata": "GAJ",
    "Yamoussoukro": "YAO",
    "Yangon": "RGN",
    "Yerevan": "EVN",
    "Zagreb": "ZAG",
    "Zanzibar": "ZNZ",
    "Zaragoza": "ZAZ",
    "Zhengzhou": "CGO",
    "Ziguinchor": "ZIG",
    "Zürich": "ZRH",
    "Zwolle": "ZWO",
};
















